apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-plugin
spec:
  selector:
    matchLabels:
      name: node-plugin
  template:
    metadata:
      labels:
        name: node-plugin
    spec:
      containers:
      - name: csi-driver-registrar
        image: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.5.0
        args:
          - "--csi-address=/csi/csi.sock"
          - "--kubelet-registration-path=/var/lib/kubelet/plugins/ccp.sai.dev/csi.sock"
          - "-v=5"
        volumeMounts:
          - name: plugin-dir
            mountPath: /csi
          - name: registration-dir
            mountPath: /registration
      - image: stark985/bsos:0.0.10
        name: node-plugin
        args:
        - "--endpoint=$(CSI_ENDPOINT)"
        env:
          - name: CSI_ENDPOINT
            value: "unix:///csi/csi.sock"  
        volumeMounts:
          - name: plugin-dir
            mountPath: /csi  
      volumes:
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry/
            type: Directory
        - name: plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins/ccp.sai.dev/
            type: DirectoryOrCreate
